### ISSUE TITLE
error in next Js  13

### ISSUE THREAD

**Issue by himanshu8443** [lijinke666/react-music-player#543]
### Version
4.24.2
### Description
after installing when I start the server npm run dev I got this error

next js 13.4.9
I am using 'use client'

### Steps

``` js
/**
 - error node_modules\react-jinke-music-player\lib\index.js (120:0) @ eval
- error TypeError: _sortablejs.Swap is not a constructor
    at __webpack_require__ (C:\Users\dm247\OneDrive\Desktop\Next\my-app\.next\server\webpack-runtime.js:33:43)
    at eval (./src/components/Player.jsx:14:82)
    at (sc_client)/./src/components/Player.jsx (C:\Users\dm247\OneDrive\Desktop\Next\my-app\.next\server\app\page.js:2027:1)
    at __webpack_require__ (C:\Users\dm247\OneDrive\Desktop\Next\my-app\.next\server\webpack-runtime.js:33:43)
null
 */
```

**Comment by Sachio-haise** [comment]
me too I am facing that error. Still can't find the solution

**Comment by TeaByte** [comment]
same here

**Comment by pomeloking01** [comment]
i work fine  using dynamic  import player
